# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.srcs/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048.xci
# IP: The module: 'async_fifo_16x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.srcs/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048.xci
# IP: The module: 'async_fifo_16x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Ayush/Xilinx/edge_detection_v2/edge_detection_v2.gen/sources_1/ip/async_fifo_16x2048/async_fifo_16x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_16x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
